# Container-based Precise due to `sudo: false`
sudo: false
language: go
go:
 - 1.5
 - 1.4
 - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/appdash
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/appdash

install:
  - go get -v github.com/influxdata/influxdb
  # see: github.com/influxdata/influxdb/issues/5388
  - mv $HOME/gopath/src/github.com/influxdata/influxdb $HOME/gopath/src/github.com/influxdb/influxdb
  - go get -t -v ./...
  - go test -v ./...
